version: "3.6"

services:
  # ============================= b4e tp =============================
  b4e-tp-0:
    restart: unless-stopped
    image: blockchain4education/b4e-transaction-processor:${B4E_VERSION}
    command: |
      bash -c "
        sleep 1
        echo start
        b4e-tp -v -C tcp://validator-0:4004
        echo b4e-tp-0 connect
      "

  b4e-tp-1:
    restart: unless-stopped
    image: blockchain4education/b4e-transaction-processor:${B4E_VERSION}
    command: |
      bash -c "
        sleep 1
        b4e-tp -v -C tcp://validator-1:4004
        echo b4e-tp-1 connect
      "

  b4e-tp-2:
    restart: unless-stopped
    image: blockchain4education/b4e-transaction-processor:${B4E_VERSION}
    command: |
      bash -c "
        sleep 1
        b4e-tp -v -C tcp://validator-2:4004
        echo b4e-tp-2 connect
      "

  b4e-tp-3:
    restart: unless-stopped
    image: blockchain4education/b4e-transaction-processor:${B4E_VERSION}
    command: |
      bash -c "
        sleep 1
        b4e-tp -v -C tcp://validator-3:4004
        echo b4e-tp-3 connect
      "

  b4e-tp-4:
    restart: unless-stopped
    image: blockchain4education/b4e-transaction-processor:${B4E_VERSION}
    command: |
      bash -c "
        sleep 1
        b4e-tp -v -C tcp://validator-4:4004
        echo b4e-tp-4 connect
      "

  # ============================= b4e-rest-api =============================
  b4e-rest-api:
    restart: unless-stopped
    image: blockchain4education/b4e-rest-api:${B4E_VERSION}
    expose:
      - 8000
    ports:
      - "8005:8000"
    command: |
      bash -c "
        b4e-rest-api \
          -B b4e-rest-api:8000 \
          -C validator-0:4004 \
          -R rest-api-0:8008 \
          --db-host ministry-mongo-db \
          --db-user ${MINISTRY_MONGO_USERNAME} \
          --db-password ${MINISTRY_MONGO_PASSWORD} \
          -vv
      "
    depends_on:
      - rest-api-0
      - validator-0
      - ministry-mongo-db

  # ============================= b4e-subscriber =============================
  b4e-subscriber:
    restart: unless-stopped
    image: blockchain4education/b4e-subscriber:${B4E_VERSION}
    command: |
      bash -c "
        b4e-subscriber subscribe \
        --db-host ministry-mongo-db \
        --db-user ${MINISTRY_MONGO_USERNAME} \
        --db-password ${MINISTRY_MONGO_PASSWORD} \
        --rest-api-default rest-api-0:8008  \
        --subscriber-host-url https://ministry-backend.b4e.vn:8000 \
        -C tcp://validator-0:4004 \
        -vv
      "
    depends_on:
      - ministry-mongo-db
      - validator-0

  # ============================= ministry-database =============================
  ministry-mongo-db:
    restart: unless-stopped
    image: mongo
    expose:
      - 27017
    # close this port if you do not need it?
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MINISTRY_MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MINISTRY_MONGO_PASSWORD}
    volumes:
      - ministry_mongodb:/data/db

  # ============================= ministry-web-backend =============================
  ministry-web-backend:
    restart: unless-stopped
    image: blockchain4education/ministry-web-backend:${B4E_VERSION}
    expose:
      - 8000
    ports:
      - "8000:8000"
    environment:
      - MONGODB_CONNECT_STRING=mongodb://${MINISTRY_MONGO_USERNAME}:${MINISTRY_MONGO_PASSWORD}@ministry-mongo-db:27017/B4E_Ministry_Backend?authSource=admin&readPreference=primary&ssl=false
      - REST_API_URL=http://b4e-rest-api:8000
      - TOKEN_SECRET
      - MINISTRY_ACCOUNT_EMAIL
      - MINISTRY_ACCOUNT_PASSWORD
    volumes:
      - type: bind
        source: /etc/letsencrypt/
        target: /etc/letsencrypt/
    depends_on:
      - ministry-mongo-db
    command: ["run", "start-https"]

  # ============================= ministry-web-frontend =============================
  ministry-web-frontend:
    restart: unless-stopped
    image: blockchain4education/ministry-web-frontend:${B4E_VERSION}
    expose:
      # - 80
      - 443
    ports:
      # - "3000:80"
      - "3000:443"
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/conf.d/default.conf
      - type: bind
        source: /etc/letsencrypt/
        target: /etc/letsencrypt/
    depends_on:
      - ministry-web-backend

volumes:
  ministry_mongodb:
